input {
  file {
    path => "/usr/share/logstash/logs/combined.log"
    start_position => "beginning"
    codec => "json"
    tags => ["rapidride"]
  }
  
  beats {
    port => 5044
  }
}

filter {
  if [tags] and "rapidride" in [tags] {
    json {
      source => "message"
    }
    
    date {
      match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
    }
    
    if [level] == "error" {
      mutate {
        add_tag => [ "error" ]
      }
    }
    
    if [service] {
      mutate {
        add_field => { "service_name" => "%{service}" }
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "rapidride-logs-%{+YYYY.MM.dd}"
  }
  
  stdout {
    codec => rubydebug
  }
}
